### PR TITLE
WIP: a first notebook tutorial

### PR DESCRIPTION
**Pull request by TristanBilot**
## Proposed changes

Support for tutorial guides, embedded directly within notebooks.

### CODE REVIEW

**Comment by TristanBilot** [comment]
I propose to write tutorials directly in notebooks so that we can embed them in the docs like in [here](https://nbsphinx.readthedocs.io/en/0.6.0/gallery/cell-metadata.html).

**Comment by TristanBilot** [comment]
@francescofarina do not hesitate to edit parts of the quickstart as needed. You can also present some of the graph operations you implemented if you think it's appropriate.

**Comment by francescofarina** [comment]
This is very cool @TristanBilot!

**Comment by francescofarina** [comment]
@TristanBilot can we merge this and then iterate on more tutorial examples?

**Comment by TristanBilot** [comment]
Yes we can merge

**Pull request merged**
