### PR TITLE
enhance prediction using leakyrelu and maxpooling

### PR DESCRIPTION
**Pull request by thegodone**
## Proposed changes

Improve the prediction using very little modification (leaky relu / maxpooling)

## Checklist

Put an `x` in the boxes that apply.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by francescofarina** [comment]
As said in https://github.com/mlx-graphs/mlx-graphs/issues/132 I'd prefer focusing on the simplicity of the tutorial rather than performance. Let me know if you think otherwise @thegodone @TristanBilot

**Comment by TristanBilot** [comment]
Am I the only one to get this error https://github.com/mlx-graphs/mlx-graphs/issues/136 when running the notebook?

**Comment by TristanBilot** [comment]
As mentioned by @francescofarina, the purpose of this notebook isn't performance. However, you may want to write your own notebook where you detail how to reach a high performance on a specific dataset @thegodone, wdyt?

**Comment by francescofarina** [comment]
Closing this as we'll keep the example as simple as possible.

**Pull request closed without merging**
