### PR TITLE
add is_directed and is_undirected to GraphData

### LINKED ISSUE #114: Add some util methods to GraphData
We would enjoy to run some graph util methods directly from the `GraphData` object.

**Ex:**
```python
g = GraphData(...)
>>> g.is_undirected()
>>> g.is_directed()
>>> g.has_self_loops()
>>> g.has_isolated_nodes()
```

Some of these functions are already implemented in mlx-graphs and can be simply called, like `is_undirected` and `is_directed`. Others need to be implemented.

### PR DESCRIPTION
**Pull request by francescofarina**
## Proposed changes

Adding `is_directed` and `is_undirected` methods to `GraphData`. Closes #114.

## Checklist

Put an `x` in the boxes that apply.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Review by TristanBilot — APPROVED** [review]

**Comment by TristanBilot** [comment]
Shall we add few tests?

**Comment by francescofarina** [comment]
the methods are already tested [here](https://github.com/mlx-graphs/mlx-graphs/blob/main/tests/utils/test_topology.py)

**Comment by TristanBilot** [comment]
Yeah, I meant to test the method in the GraphData object itself, just to ensure the class has this method, but if you don't think this is mandatory let's not add it.

**Comment by francescofarina** [comment]
> Yeah, I meant to test the method in the GraphData object itself, just to ensure the class has this method, but if you don't think this is mandatory let's not add it.

Yes, done!

**Comment by TristanBilot** [comment]
Good!

**Pull request merged**
