### PR TITLE
Benchmarks (scatter/gather)

### PR DESCRIPTION
**Pull request by TristanBilot**

### CODE REVIEW

**Comment by TristanBilot** [comment]
@francescofarina could you run the `launcher.py` locally and append your results to `gather_scatter_benchmark.md`?
I need to try multiple devices in order to check how the hardware influences the scatter and gather operations.

Also, what is your config?

**Comment by francescofarina** [comment]
Will do! I have an M3 Pro with 18GB of RAM.

**Comment by francescofarina** [comment]
@TristanBilot just added my results - the trend is the same (except for gather which performs worse) but there's a lot of variability

**Review by TristanBilot — COMMENTED** [review]
Thanks! Hmm very strange that it's so slower on your M3 Pro than on my M1 Pro, did you run many heavy programs while running the bench? (many Google Chrome tables etc?)

**Comment by francescofarina** [comment]
Actually, wait - I guess you ran them with the latest dev version of mlx (not the released 0.1). With the version on the main branch of of the git repo results are significantly better:

Detailed benchmark:
| Operation                                                              | mlx_gpu | mlx_cpu | pyg_cpu | mlx_gpu/pyg_cpu speedup |
|------------------------------------------------------------------------|-------|-------|-------|-----------------------|
| benchmark_scatter / edg=(2, 1000) nod=(10, 64) sca=add             |   0.52 |   0.48 |   0.12 |    -76% |
| benchmark_scatter / edg=(2, 10000) nod=(10, 64) sca=add            |   1.88 |   4.94 |   1.45 |    -23% |
| benchmark_scatter / edg=(2, 100000) nod=(10, 64) sca=add           |   7.69 |  23.29 |   3.62 |    -53% |
| benchmark_scatter / edg=(2, 1000000) nod=(10, 64) sca=add          |  44.64 | 194.25 |  36.46 |    -18% |
| benchmark_scatter / edg=(2, 1000) nod=(100, 64) sca=add            |   0.55 |   0.56 |   0.14 |    -74% |
| benchmark_scatter / edg=(2, 10000) nod=(100, 64) sca=add           |   1.80 |   5.07 |   1.20 |    -33% |
| benchmark_scatter / edg=(2, 100000) nod=(100, 64) sca=add          |   7.23 |  19.55 |   2.80 |    -61% |
| benchmark_scatter / edg=(2, 1000000) nod=(100, 64) sca=add         |  44.49 | 194.22 |  31.31 |    -29% |
| benchmark_scatter / edg=(2, 1000) nod=(1000, 64) sca=add           |   0.73 |   0.62 |   0.16 |    -77% |
| benchmark_scatter / edg=(2, 10000) nod=(1000, 64) sca=add          |   1.94 |   5.59 |   0.97 |    -49% |
| benchmark_scatter / edg=(2, 100000) nod=(1000, 64) sca=add         |   7.02 |  19.49 |   2.78 |    -60% |
| benchmark_scatter / edg=(2, 1000000) nod=(1000, 64) sca=add        |  44.51 | 193.88 |  30.65 |    -31% |
| benchmark_scatter / edg=(2, 1000) nod=(10000, 64) sca=add          |   0.83 |   0.80 |   0.45 |    -45% |
| benchmark_scatter / edg=(2, 10000) nod=(10000, 64) sca=add         |   1.91 |   5.37 |   1.20 |    -37% |
| benchmark_scatter / edg=(2, 100000) nod=(10000, 64) sca=add        |   6.65 |  20.44 |   3.09 |    -53% |
| benchmark_scatter / edg=(2, 1000000) nod=(10000, 64) sca=add       |  44.57 | 194.31 |  30.67 |    -31% |
| benchmark_gather / edg=(2, 1000) nod=(10, 64)                      |   0.34 |   0.11 |   0.24 |    -27% |
| benchmark_gather / edg=(2, 10000) nod=(10, 64)                     |   0.75 |   0.53 |   1.56 |   +106% |
| benchmark_gather / edg=(2, 100000) nod=(10, 64)                    |   4.37 |   6.87 |   5.66 |    +29% |
| benchmark_gather / edg=(2, 1000000) nod=(10, 64)                   |  12.99 |  36.48 |  26.86 |   +106% |
| benchmark_gather / edg=(2, 1000) nod=(100, 64)                     |   0.35 |   0.09 |   0.25 |    -28% |
| benchmark_gather / edg=(2, 10000) nod=(100, 64)                    |   1.23 |   0.55 |   1.30 |     +5% |
| benchmark_gather / edg=(2, 100000) nod=(100, 64)                   |   2.79 |   6.13 |   5.85 |   +109% |
| benchmark_gather / edg=(2, 1000000) nod=(100, 64)                  |  14.36 |  36.77 |  26.61 |    +85% |
| benchmark_gather / edg=(2, 1000) nod=(1000, 64)                    |   0.50 |   0.09 |   0.29 |    -42% |
| benchmark_gather / edg=(2, 10000) nod=(1000, 64)                   |   1.58 |   0.78 |   1.29 |    -18% |
| benchmark_gather / edg=(2, 100000) nod=(1000, 64)                  |   3.93 |   7.48 |   6.00 |    +52% |
| benchmark_gather / edg=(2, 1000000) nod=(1000, 64)                 |  14.71 |  38.87 |  27.23 |    +85% |
| benchmark_gather / edg=(2, 1000) nod=(10000, 64)                   |   0.41 |   0.84 |   0.24 |    -41% |
| benchmark_gather / edg=(2, 10000) nod=(10000, 64)                  |   0.63 |   0.71 |   1.52 |   +143% |
| benchmark_gather / edg=(2, 100000) nod=(10000, 64)                 |   2.44 |   9.47 |   2.87 |    +17% |
| benchmark_gather / edg=(2, 1000000) nod=(10000, 64)                |  14.50 |  39.93 |  27.74 |    +91% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 1000) nod=(10, 64)       |   0.96 |   0.74 |   0.39 |    -59% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 10000) nod=(10, 64)      |   2.31 |   6.13 |   2.52 |     +8% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 100000) nod=(10, 64)     |   7.36 |  24.58 |   5.48 |    -25% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 1000000) nod=(10, 64)    |  53.55 | 249.05 |  67.22 |    +25% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 1000) nod=(100, 64)      |   1.65 |   0.90 |   0.55 |    -66% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 10000) nod=(100, 64)     |   1.83 |   6.03 |   2.67 |    +45% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 100000) nod=(100, 64)    |   8.07 |  25.20 |   5.54 |    -31% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 1000000) nod=(100, 64)   |  53.44 | 249.53 |  66.36 |    +24% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 1000) nod=(1000, 64)     |   1.10 |   1.04 |   0.77 |    -30% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 10000) nod=(1000, 64)    |   2.34 |   6.36 |   3.19 |    +36% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 100000) nod=(1000, 64)   |   9.40 |  25.22 |   5.70 |    -39% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 1000000) nod=(1000, 64)  |  53.46 | 250.78 |  64.50 |    +20% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 1000) nod=(10000, 64)    |   1.28 |   3.11 |   3.95 |   +208% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 10000) nod=(10000, 64)   |   2.67 |   7.67 |   5.46 |   +104% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 100000) nod=(10000, 64)  |   7.42 |  25.65 |   7.00 |     -5% |
| benchmark_GCNConv / in_=64 out=64 edg=(2, 1000000) nod=(10000, 64) |  53.54 | 251.35 |  65.88 |    +23% |

 Average benchmark:
| Operation              | mlx_gpu | mlx_cpu | pyg_cpu | mlx_gpu/pyg_cpu speedup |
|------------------------|-------|-------|-------|-----------------------|
| benchmark_scatter  |  13.56 |  55.18 |   9.19 |    -32% |
| benchmark_gather   |   4.74 |  11.61 |   8.47 |    +78% |
| benchmark_GCNConv  |  16.27 |  70.83 |  19.20 |    +17% |

**Comment by francescofarina** [comment]
@TristanBilot let me know which version you're using and I'll update the benchmark accordingly

**Comment by TristanBilot** [comment]
I tried a greedy approach to switch device from GPU to CPU for the operations with small shapes faster on CPU than GPU. However, it seems that this switch still takes some time and we don't get the exact same results as in the CPU column.
You can try locally to see how this improves speedup on your M3 Pro. On my side I improved in average from +29% to +66%.

**Comment by francescofarina** [comment]
> I tried a greedy approach to switch device from GPU to CPU for the operations with small shapes faster on CPU than GPU. However, it seems that this switch still takes some time and we don't get the exact same results as in the CPU column. You can try locally to see how this improves speedup on your M3 Pro. On my side it improved in average from +29% to +66%.

Interesting - these are the results on my end

 Average benchmark:
| Operation                  | mlx_gpu | mlx_cpu | pyg_cpu | mlx_gpu/pyg_cpu speedup |
|----------------------------|-------|-------|-------|-----------------------|
| benchmark_gather       |   3.71 |  11.54 |   8.42 |   +127% |
| benchmark_fast_gather  |   3.82 |   3.21 |   8.98 |   +135% |

**Comment by francescofarina** [comment]
@TristanBilot have you tried using `timeit` instead of doing it manually? (I did that in https://github.com/TristanBilot/mlx-graphs/blob/main/benchmarks/col_vs_row_edge_index/launcher.py)

**Comment by TristanBilot** [comment]
No I didn't try it. I'm not sure it's the reason but we can give it a try.

**Comment by francescofarina** [comment]
@TristanBilot I migrated the code to use `timeit` - can you please re-run the experiments on your device?

An interesting pattern I see is that there's a clear advantage of using `mlx` as the problem dimension increases (except for scatter ops which still don't perform as well).

**Comment by francescofarina** [comment]
Also interesting how, on my end, gather ops are consistently faster for 10k and 1M features, but slower for 100k features.

**Comment by TristanBilot** [comment]
I reported my results with `timeit`. It's indeed more stable, but PyG benchmarks are also slower (?).

| Operation                  | mlx_gpu | mlx_cpu | pyg_cpu | mlx_gpu/pyg_cpu speedup |
|----------------------------|-------|-------|-------|-----------------------|
| benchmark_gather       |   3.59 |   7.16 |   9.85 |   +174% |
| benchmark_fast_gather  |   3.60 |   3.36 |   9.69 |   +169% |

It's super strange that it's slower on your M3 Pro though...

**Comment by TristanBilot** [comment]
Also, it seems that my greedy improvement does not improve performance at all. And yeah, it looks like it's worth it to use mlx operations on large data instead of small data. That's why we need to leverage batching a maximum.

**Comment by francescofarina** [comment]
It's actually faster on my M3. There's less speedup but it's still faster in absolute terms. Also, from what I see comparing the new results with the old ones, PyG is not slower when using `timeit` (actually it's faster), no?

**Comment by francescofarina** [comment]
Do you have some specific problem you'd like to test? I was looking at QM9 for quantum-chemical property prediction on molecules.

**Comment by TristanBilot** [comment]
Yep it would be a nice example. This dataset contains many graphs that we can batch, but the graphs are very small (~37 edges/graph) so it may be interesting to see if it performs well in such situation.
BTW, I'm working on a quickstart example rn.

**Comment by francescofarina** [comment]
New performance results as of https://github.com/ml-explore/mlx/commit/06072601cef7876a23d079d9f8c28df28f6e28e8 on M3 Pro


 Average benchmark:
| Operation                  | mlx_gpu | mlx_cpu | pyg_cpu | mlx_gpu/pyg_cpu speedup |
|----------------------------|-------|-------|-------|-----------------------|
| benchmark_scatter      |   3.40 |  52.97 |   8.24 |   +142% |
| benchmark_gather       |   3.01 |   4.94 |   7.18 |   +138% |
| benchmark_fast_gather  |   3.10 |   2.91 |   7.31 |   +136% |
| benchmark_GCNConv      |   6.32 |  61.60 |  17.32 |   +173% |

**Comment by TristanBilot** [comment]
WoW seems amazing, is it a 4x improvement on scatter?

**Comment by francescofarina** [comment]
Close #82 with de0a672

**Comment by TristanBilot** [comment]
@francescofarina could you append your results with the new scatter so that we keep trace of the speedup improvements and we can merge? thx!

**Comment by francescofarina** [comment]
> @francescofarina could you append your results with the new scatter so that we keep trace of the speedup improvements and we can merge? thx!

Yes, I added the full results - it's interesting that on M1 GCN and GAT are still slower.

**Comment by francescofarina** [comment]
@TristanBilot any chances you can re-run the experiments for GCN and GAT before merging? The performance on the M1 is quite weird

**Comment by francescofarina** [comment]
Closing this as I moved the benchmarks to #89. @TristanBilot feel free to add your results there.

**Pull request closed without merging**
