### PR TITLE
Add new dataset class for HeterographData

### PR DESCRIPTION
**Pull request by vinayhpandya**
Added new dataset class for Heterograph data

1. Type errors in IMDB and DBLP tests are occurring because the 'Dataset' placeholder is being used to represent both 'HeteroGraphData' and 'GraphData' types.`
2.  Replaced IMDB and DBLP datasets with HeteroGraph dataset to resolve the type errors

## Proposed changes

Please include a description of the problem or feature this PR is addressing.
If there is a corresponding issue, include the issue #.

## Checklist

Put an `x` in the boxes that apply.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Review by francescofarina — CHANGES_REQUESTED** [review]
I believe this needs a bit more refactoring. We probably want to have a base dataset class from which both `Dataset` and `HeteroGraphDataset` inherit, which contains the shared logic and abstract methods. Right now the `Dataset` class can still accept `HeteroGraphData` objects as inputs, which shouldn't be allowed. @vinayhpandya what do you think?

@vinayhpandya

**Comment by vinayhpandya** [comment]
I think its a good Idea, we can keep `process`,`load` and download function in the parent class and let dataset and heterographdataset class inherit those. @francescofarina what do you think?

**Comment by francescofarina** [comment]
Yes, I believe the parent class could also handle _most_ of the property methods though (like the name, the paths and the number of graphs)

**Review by TristanBilot — APPROVED** [review]
Seems OK to me!

**Pull request merged**
