### PR TITLE
Convert to nx

### PR DESCRIPTION
**Pull request by Kheims**
## Proposed changes

Simple utility function to convert an mlx GraphData object to a networkx object to facilitate visualisation of subgraphs of Neighbor Sampler (#94)

## Checklist

Put an `x` in the boxes that apply.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by Kheims** [comment]
Note : I haven't added conversion of graphs intrinsic attributes but only relevant structural information for strictly visualisation purposes.

**Comment by TristanBilot** [comment]
Nice initiative @Kheims 🚀 I just pushed some minor fixes. Btw, you don't need to add the type hints in the function docstring as it's automatically infered by Sphinx based on the function signature.

**Comment by TristanBilot** [comment]
Also, @francescofarina I think it would be better to return 0 is `num_nodes` instead of None when there's no nodes, wdyt?

**Comment by Kheims** [comment]
Oh i didn't know that, thanks for the info and fixes

**Comment by francescofarina** [comment]
> Also, @francescofarina I think it would be better to return 0 is `num_nodes` instead of None when there's no nodes, wdyt?

Yes, otherwise we have to always make the check to avoid type hinting issues.

**Pull request merged**
